**SUBMISSION INSTRUCTIONS**

It is recommendend that you make a copy of this colab file and then solve the assignment and upload your final notebook on github.

Before uploading your downloaded notebook, **RENAME** the file as **rollno_name.ipynb**

**Submission Deadline : 9/12/2025 Tuesday EOD i.e before 11:59 PM**

The deadline is strict and will not be extended, Late submissions are not allowed

Note that you have to upload your solution on the github page of the project Vision Transformer and under Week0

**Github Submission repo** -
https://github.com/electricalengineersiitk/Winter-projects-25-26/tree/main/Vision%20transformer/Week0

#**Assignment 1**
#**Section 1 (Python)**
#**Problem 1**
In this problem, you will implement a class that represents a data sample with numerical features.  
##  Problem Statement
Create a class named **`DataSample`** that stores:

- A list of numeric **features**
- A string **label**

You must implement the following **three methods** with **exact names** (do NOT rename them):

| Method | Description |
|--------|------------|
| `__init__(self, features, label)` | Initializes object attributes |
| `min_max_norm(self)` | Apply min-max normalization **in-place** |
| `scaled(self, factor)` | Return a **new list** with each feature multiplied by `factor` |

### Min–Max Normalization Formula

![Alt text for the image](https://miro.medium.com/v2/resize:fit:964/1*OnCBKS-Thqa43qNslohDpA.png)


###  Edge Case
If **all features are equal**, then max = min → division by zero.  
Handle this condition by setting all normalized values to **0**.

---

### Your output must behave conceptually like this (not real execution here):
```python
sample = DataSample([10, 20, 30], "cat")
sample.min_max_norm()
print(sample.features)   # expected -> [0.0, 0.5, 1.0]

print(sample.scaled(2))  # expected -> [0.0, 1.0, 2.0]


**Sample Class**

In [27]:
class DataSample:
    def __init__(self, features, label):
        """
        Initialize the object with feature list and label string.
        """
        self.features = features
        self.label = label

    def min_max_norm(self):
        """
        Apply min-max normalization:
        Modify self.features in-place.
        Handle case where max == min.
        """
        min_val = min(self.features)
        max_val = max(self.features)
        if min_val == max_val:
            self.features = [0.0] * len(self.features)
            return
        self.features = [
            (x - min_val) / (max_val - min_val)
            for x in self.features
        ]

    def scaled(self, factor):
        """
        Return a NEW list of features where each element is multiplied by factor.
        """
        return [x * factor for x in self.features]

You can check if your code is working correctly using the sample case below

In [28]:
sample = DataSample([3.5, -2.0, 3.5, 10.0, 0.0], "bird")

print("Original features:", sample.features)
print("Label:", sample.label)

sample.min_max_norm()
print("After min-max normalization:", sample.features)

scaled_output = sample.scaled(4.2)
print("After scaling x 4.2 (new list expected):", scaled_output)

# Expected Output:
# Original features: [3.5, -2.0, 3.5, 10.0, 0.0]
# Label: bird
# After min-max normalization: [0.395, 0.0, 0.395, 1.0, 0.2]   (approx values)
# After scaling x 4.2: [1.659, 0.0, 1.659, 4.2, 0.84]

Original features: [3.5, -2.0, 3.5, 10.0, 0.0]
Label: bird
After min-max normalization: [0.4583333333333333, 0.0, 0.4583333333333333, 1.0, 0.16666666666666666]
After scaling x 4.2 (new list expected): [1.925, 0.0, 1.925, 4.2, 0.7]


#**Problem 2**
Sort Based on Unique Character Count

Write a function named **`sort_by_unique_chars`** that sorts a list of strings based on the number of **unique characters** in each string (**descending** order).  
If two strings have the same number of unique characters, sort them **alphabetically**.

Assume that the characters in the words are only consisting of lower-case english alphabets

### Function Definition (DO NOT CHANGE THIS NAME)

```python
def sort_by_unique_chars(words):
    return sorted(
        words,
        key=lambda w: (-len(set(w)), w)
    )

In [29]:
def sort_by_unique_chars(words):
    return sorted(
        words,
        key=lambda w: (-len(set(w)), w)   # negative for descending, w for alphabetical
    )

check your code by running the below block

In [30]:
#example case
input_data = ["apple", "banana", "kiwi", "grape", "mango"]
output = sort_by_unique_chars(input_data)
print(output)
# Expected Output:
# ['grape', 'mango', 'apple', 'banana', 'kiwi']

['grape', 'mango', 'apple', 'banana', 'kiwi']


# **Section 2 (NumPy)**
# **Problem 1**

In this problem, you will work with NumPy arrays to practice masking, slicing, advanced indexing, and broadcasting. Follow each step sequentially using only NumPy operations (no Python loops).

## **Problem Statement**

1. **Generate** a 10×10 NumPy array `X` containing random integers between **0 and 100** (inclusive).

2. Create a **boolean mask** selecting all values between **20 and 50** (inclusive).   
   Using this mask, replace those values in `X` with **−1** *in-place*.

3. Extract a **6×6 submatrix** `sub` from the modified `X`:
   - Rows **2 to 8**
   - Columns **3 to 9**

4. Using **advanced NumPy indexing**, extract all **diagonal elements** of the 6×6 submatrix `sub` into a 1D array `diag_vals`.  
   *Hint: use* `np.arange(6)`.

5. Construct a **10×10 structured matrix** `M` using broadcasting, where:

    `M[i, j] = (i - j)²`

    for all `0 ≤ i, j < 10`. This must be done **without loops**.


In [31]:
import numpy as np
X = np.random.randint(0, 101, size=(10, 10))
mask = (X >= 20) & (X <= 50)
X[mask] = -1
sub = X[2:8, 3:9]
indices = np.arange(6)
diag_vals = sub[indices, indices]
i = np.arange(10).reshape(-1, 1)
j = np.arange(10).reshape(1, -1)
M = (i - j) ** 2

# **Problem 2**

In this problem, you will work with NumPy arrays representing class scores for multiple samples.
You will practice row-wise normalization, broadcasting, and boolean masking.

## **Problem Statement**

1. Create a NumPy array `scores` of shape 5×4 containing integer values between **0 and 20** (inclusive).  
   Each row represents a sample, and each column represents a score for one of the 4 classes.

2. For each row in `scores`, subtract the **maximum value of that row** from all elements in that row.  
   This operation must be performed using **broadcasting** (no loops allowed).

   *Hint:*  
   `scores.max(axis=1, keepdims=True)` produces a (5×1) column of row-wise maxima.

3. Compute a new array `exp_scores` by applying the exponential function to each element:

   `exp_scores = np.exp(shifted_scores)`

4. **Normalize each row** of `exp_scores` so that each row sums to **1**.  
   Store the resulting array in `probs`.  

   The transformation is conceptually shown by the formula:

   <img src="https://miro.medium.com/v2/resize:fit:300/1*bol3L-WNVacCscvG-rlypQ.png" width="250"/>

   Which corresponds to:

   `probs[i, j] = exp_scores[i, j]/sum(exp_scores[i, :])`

5. Compute the **predicted class** for each sample by taking the index of the largest value in each row of `probs`.  
   Store this in a 1D array `y_pred` of length 5.

6. Create a NumPy array `y_true` of length 5 containing the true class labels (each between 0 and 3).

7. Create a boolean array `correct_mask` indicating whether each predicted label matches the true label.  
   Then compute the **accuracy** using:

   `accuracy = correct_mask.mean()`


In [32]:
import numpy as np
scores = np.random.randint(0, 21, size=(5, 4))
row_max = scores.max(axis=1, keepdims=True)
shifted_scores = scores - row_max
exp_scores = np.exp(shifted_scores)
row_sums = exp_scores.sum(axis=1, keepdims=True)
probs = exp_scores / row_sums
y_pred = probs.argmax(axis=1)
y_true = np.random.randint(0, 4, size=5)
correct_mask = (y_pred == y_true)
accuracy = correct_mask.mean()
print("scores:\n", scores)
print("shifted_scores:\n", shifted_scores)
print("probs:\n", probs)
print("y_pred:", y_pred)
print("y_true:", y_true)
print("correct_mask:", correct_mask)
print("accuracy:", accuracy)

scores:
 [[ 7  1  4  8]
 [18 20  8 16]
 [ 1 20 14  6]
 [ 4  0  7 12]
 [15 14  0  4]]
shifted_scores:
 [[ -1  -7  -4   0]
 [ -2   0 -12  -4]
 [-19   0  -6 -14]
 [ -8 -12  -5   0]
 [  0  -1 -15 -11]]
probs:
 [[2.65213463e-01 6.57398449e-04 1.32042008e-02 7.20924938e-01]
 [1.17309803e-01 8.66808716e-01 5.32585682e-06 1.58761554e-02]
 [5.58893817e-09 9.97526544e-01 2.47262109e-03 8.29471969e-07]
 [3.33104397e-04 6.10101985e-06 6.69058067e-03 9.92970214e-01]
 [7.31049489e-01 2.68938078e-01 2.23629735e-07 1.22097698e-05]]
y_pred: [3 1 1 3 0]
y_true: [2 0 1 1 1]
correct_mask: [False False  True False False]
accuracy: 0.2


#Section 3 - Pandas and MatPlotLib


#Creating Batches for Training and Testing Using Pandas

Download the following .csv file from the given link directly using commands in colab - url = "https://raw.githubusercontent.com/rashida048/Datasets/master/StudentsPerformance.csv"

In [33]:
import pandas as pd

Import the csv file as a dataframe

In [34]:
df = pd.read_csv("StudentsPerformance.csv")

Write the command to be able to see the first 5 rows

In [35]:
df.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

Create multiple dataframes with the following columns sorted : gender, race, math, reading and writing scores.

(meaning create df1, df2, df3 etc. with the math score sorted in df1, gender wise sorted in df2 etc.)

In [36]:
# gender
df_gender = df.sort_values(by="gender")

In [37]:
# race/ethnicity
df_race = df.sort_values(by="race/ethnicity")

In [38]:
# math
df_math = df.sort_values(by="math score")

In [39]:
# reading
df_reading = df.sort_values(by="reading score")

In [40]:
# writing
df_writing = df.sort_values(by="writing score")

In [41]:
print(df_gender.head())
print(df_race.head())
print(df_math.head())
print(df_reading.head())
print(df_writing.head())

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
563  female        group D                some college  free/reduced   
566  female        group E           bachelor's degree  free/reduced   
567  female        group D             master's degree  free/reduced   
572  female        group C                some college      standard   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
563               completed          63             80             80  
566               completed          92            100            100  
567               completed          61             71             78  
572                    none          53             62             56  
     gender race/ethnicity parental level of education         lunch  \
778  female        group A                some college      sta

Create 2 non-overlapping dataframes test_df and train_df such that 20% of the rows are in test_df and the rest in train_df

In [42]:
import pandas as pd
df_shuffled = df.sample(frac=1, random_state=42)
test_size = int(0.2 * len(df_shuffled))

In [43]:
test_df = df_shuffled.iloc[:test_size]
train_df = df_shuffled.iloc[test_size:]

Plot a bar graph such that you can see the distribution of race in test and train dataset. Are the proportions of races almost same in train and test datasets ? If not what can you do so that the proportions of races in the test and train datasets are close ?


Hint : Think Sorting on the race/ethnicity column and then applying some logic.

In [44]:
# to clarify if the split of races A, B, C, D and E are nearly say 0.2, 0.15, 0.25, 0.17, 0.23
# then I expect an almost similar split in the train_df and test_df

In [45]:
import pandas as pd
test_parts = []
train_parts = []
for race, group in df.groupby("race/ethnicity"):
    n_test = int(0.2 * len(group))
    group_shuffled = group.sample(frac=1, random_state=42)
    test_parts.append(group_shuffled.iloc[:n_test])
    train_parts.append(group_shuffled.iloc[n_test:])
test_df = pd.concat(test_parts).sample(frac=1, random_state=42)
train_df = pd.concat(train_parts).sample(frac=1, random_state=42)

In [46]:
overall_prop = df["race/ethnicity"].value_counts(normalize=True).sort_index()
train_prop   = train_df["race/ethnicity"].value_counts(normalize=True).sort_index()
test_prop    = test_df["race/ethnicity"].value_counts(normalize=True).sort_index()
print("Overall proportions:\n", overall_prop)
print("\nTrain proportions:\n", train_prop)
print("\nTest proportions:\n", test_prop)

Overall proportions:
 race/ethnicity
group A    0.089
group B    0.190
group C    0.319
group D    0.262
group E    0.140
Name: proportion, dtype: float64

Train proportions:
 race/ethnicity
group A    0.089776
group B    0.189526
group C    0.319202
group D    0.261845
group E    0.139651
Name: proportion, dtype: float64

Test proportions:
 race/ethnicity
group A    0.085859
group B    0.191919
group C    0.318182
group D    0.262626
group E    0.141414
Name: proportion, dtype: float64


Even if it the proportions are almost same think of a way to create the train_df and test_df to have similar proportions of races.

In [47]:
test_parts = []
train_parts = []
for race, group in df.groupby("race/ethnicity"):
    group = group.sample(frac=1, random_state=42)
    n_test = int(0.2 * len(group))
    test_parts.append(group.iloc[:n_test])
    train_parts.append(group.iloc[n_test:])
test_df = pd.concat(test_parts).sample(frac=1, random_state=42)
train_df = pd.concat(train_parts).sample(frac=1, random_state=42)

Usually when we train machine learning models we use batches. Each batch is a subset of train_df of legth batch_size. Create Batches: a list of batch each of size 50 from the train_df

In [48]:
batch_size = 50

In [49]:
Batches = [
    train_df.iloc[i : i + batch_size]
    for i in range(0, len(train_df), batch_size)
]

Print the size of Batches and first few rows of Batches[0]

In [50]:
print("Number of batches:", len(Batches))
print("\nFirst few rows of Batches[0]:")
print(Batches[0].head())

Number of batches: 17

First few rows of Batches[0]:
     gender race/ethnicity parental level of education         lunch  \
219    male        group B            some high school      standard   
278  female        group C            some high school  free/reduced   
218    male        group B                 high school  free/reduced   
920    male        group D                 high school  free/reduced   
130    male        group D             master's degree      standard   

    test preparation course  math score  reading score  writing score  
219               completed          61             56             56  
278                    none          65             86             80  
218                    none          66             77             70  
920                    none          69             70             67  
130                    none          89             84             82  
