In [ ]:

class DataSample:
    def __init__(self, features, label):
        self.features = features
        self.label = label

    def min_max_norm(self):
        if not self.features:
            return

        min_val = min(self.features)
        max_val = max(self.features)

        if max_val == min_val:
            self.features = [0 for _ in self.features]
        else:
            denom = max_val - min_val
            self.features = [(x - min_val) / denom for x in self.features]

    def scaled(self, factor):

        return [x * factor for x in self.features]

if __name__ == "__main__":
    # Test Case 1: Standard normalization
    sample = DataSample([10, 20, 30], "cat")
    sample.min_max_norm()
    print(f"Normalized features: {sample.features}")  # Expected: [0.0, 0.5, 1.0]

    # Test Case 2: Scaled method
    print(f"Scaled by 2: {sample.scaled(2)}")        # Expected: [0.0, 1.0, 2.0]

    # Test Case 3: Edge Case (all equal)
    sample_edge = DataSample([5, 5, 5], "edge_case")
    sample_edge.min_max_norm()
    print(f"Edge case features: {sample_edge.features}") # Expected: [0, 0, 0]

Normalized features: [0.0, 0.5, 1.0]
Scaled by 2: [0.0, 1.0, 2.0]
Edge case features: [0, 0, 0]


In [ ]:
def sort_by_unique_chars(words):

    return sorted(words, key=lambda x: (-len(set(x)), x))

input_data = ["apple", "banana", "kiwi", "grape", "mango"]
output = sort_by_unique_chars(input_data)
print(output)

['grape', 'mango', 'apple', 'banana', 'kiwi']


In [ ]:
import numpy as np
np.random.seed(42)
X = np.random.randint(0, 101, (10, 10))
mask = (X >= 20) & (X <= 50)
X[mask] = -1

sub = X[2:8, 3:9]

idx = np.arange(6)
diagonal_values = sub[idx, idx]

i = np.arange(10).reshape(10, 1)
j = np.arange(10).reshape(1, 10)
M = (i - j) ** 2

print("Diagonal Elements:", diagonal_values)
print("Structured Matrix M:\n", M)

Diagonal Elements: [ -1  59 100   8  -1  92]
Structured Matrix M:
 [[ 0  1  4  9 16 25 36 49 64 81]
 [ 1  0  1  4  9 16 25 36 49 64]
 [ 4  1  0  1  4  9 16 25 36 49]
 [ 9  4  1  0  1  4  9 16 25 36]
 [16  9  4  1  0  1  4  9 16 25]
 [25 16  9  4  1  0  1  4  9 16]
 [36 25 16  9  4  1  0  1  4  9]
 [49 36 25 16  9  4  1  0  1  4]
 [64 49 36 25 16  9  4  1  0  1]
 [81 64 49 36 25 16  9  4  1  0]]
