In [15]:
from google.colab import files
files.upload()


Saving HousingData.csv to HousingData (1).csv


{'HousingData (1).csv': b'CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV\r\n0.00632,18,2.31,0,0.538,6.575,65.2,4.09,1,296,15.3,396.9,4.98,24\r\n0.02731,0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.9,9.14,21.6\r\n0.02729,0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7\r\n0.03237,0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4\r\n0.06905,0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.9,NA,36.2\r\n0.02985,0,2.18,0,0.458,6.43,58.7,6.0622,3,222,18.7,394.12,5.21,28.7\r\n0.08829,12.5,7.87,NA,0.524,6.012,66.6,5.5605,5,311,15.2,395.6,12.43,22.9\r\n0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311,15.2,396.9,19.15,27.1\r\n0.21124,12.5,7.87,0,0.524,5.631,100,6.0821,5,311,15.2,386.63,29.93,16.5\r\n0.17004,12.5,7.87,NA,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.1,18.9\r\n0.22489,12.5,7.87,0,0.524,6.377,94.3,6.3467,5,311,15.2,392.52,20.45,15\r\n0.11747,12.5,7.87,0,0.524,6.009,82.9,6.2267,5,311,15.2,396.9,13.27,18.9\r\n0.09378,12.5,7.87,0,0.524,5.889,39

In [16]:
import pandas as pd
import numpy as np
df=pd.read_csv("HousingData.csv")
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     486 non-null    float64
 1   ZN       486 non-null    float64
 2   INDUS    486 non-null    float64
 3   CHAS     486 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      486 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    486 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  486.000000  486.000000  486.000000  486.000000  506.000000  506.000000   
mean     3.611874   11.211934   11.083992    0.069959    0.554695    6.284634   
std      8.720192   23.388876    6.835896    0.255340    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.081900    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.253715    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.560263   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  486.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.518519    3.795043    9.549407  408.237154   18.455534  356.674032   
std     27.999513    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.175000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     76.800000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     93.975000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  486.000000  506.000000  
mean    12.715432   22.532806  
std      7.155871    9.197104  
min      1.730000    5.000000  
25%      7.125000   17.025000  
50%     11.430000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [17]:
X=df[["LSTAT","PTRATIO","NOX","RM","AGE"]]
y=df["MEDV"]

In [18]:
#now we will create a manual scaler
import numpy as np
def manual_standardscaler(X):
    mean = X.mean(axis=0)          # CRITICAL: axis=0
    std = X.std(axis=0)             # CRITICAL: axis=0
    std[std == 0] = 1.0            # Prevent division by zero
    X_scaled = (X - mean) / std
    return X_scaled, mean, std

X_scaled, mean, std = manual_standardscaler(X)
print("\nManual scaler result shape:", X_scaled.shape)
print("\nManual scaler result:\n", X_scaled)
  #we get a scaled value for the features which is represented by X


Manual scaler result shape: (506, 5)

Manual scaler result:
         LSTAT   PTRATIO       NOX        RM       AGE
0   -1.080991 -1.457558 -0.144075  0.413263 -0.118521
1   -0.499650 -0.302794 -0.739530  0.194082  0.370774
2   -1.213749 -0.302794 -0.739530  1.281446 -0.264952
3   -1.366072  0.112920 -0.834458  1.015298 -0.811390
4         NaN  0.112920 -0.834458  1.227362 -0.511385
..        ...       ...       ...       ...       ...
501       NaN  1.175303  0.157968  0.438881  0.020768
502 -0.508035  1.175303  0.157968 -0.234316  0.292201
503 -0.988759  1.175303  0.157968  0.983986  0.802924
504 -0.871373  1.175303  0.157968  0.724955  0.742209
505 -0.675729  1.175303  0.157968 -0.362408       NaN

[506 rows x 5 columns]


In [42]:
#we will implement linear regression using gradient descent and L2 regularisation without using sklearn
import matplotlib.pyplot as plt

def regression_descent(X,y,learning_rate,num_iterations,lam=0.1):
 m,n=X.shape
 #initalise the weights w and bais b to zero
 b=0
 w=np.zeros(n)

 for i in range(num_iterations):
  y_pred=np.dot(X,w)+b
  loss=(1/(2*m))*np.sum((y_pred-y)**2)
  #gradients
  dw=(1/m)*np.dot(X.T,(y_pred-y)) +(lam/m)*w
  db=(1/m)*np.sum(y_pred-y)
  w=w-learning_rate*dw
  b=b-learning_rate*db
  if i%100==0:
    print(f"Iteration {i}: Loss={loss}")
    #plot loss vs iterations
    plt.plot(i,loss)
    plt.xlabel("Iterations")
    plt.ylabel("Loss")
    plt.show()
 return w,b

#plot true vs predicted values
import matplotlib.pyplot as plt
def plot_predictions(X,y,w,b):
  y_pred=np.dot(X,w)+b
  plt.scatter(X,y,label="True values")
  plt.scatter(X,y_pred,label="Predicted values")
  plt.xlabel("X")
  plt.ylabel("y")
  plt.legend()
  plt.show()




In [21]:
#now data upload for logisitc regression
from google.colab import files
files.upload()


# i have choosed titanic dataset we need to predict whether the person died or survived on looking at the features

Saving Titanic-Dataset.csv to Titanic-Dataset (2).csv


{'Titanic-Dataset (2).csv': b'PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked\r\n1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,,S\r\n2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1,0,PC 17599,71.2833,C85,C\r\n3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,,S\r\n4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S\r\n5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,,S\r\n6,0,3,"Moran, Mr. James",male,,0,0,330877,8.4583,,Q\r\n7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S\r\n8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.075,,S\r\n9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,,S\r\n10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,,C\r\n11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,PP 9549,16.7,G6,S\r\n12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,2

In [22]:
import pandas as pd
import numpy as np
df=pd.read_csv('Titanic-Dataset.csv')
df.info()
df.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [25]:
#we will select the suitable feautures to predict
X=df[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked']]
y=df['Survived']


In [23]:
#now we will scale the data using our manual scaler
X_scaled, mean, std = manual_standardscaler(X)
print("\nManual scaler result shape:", X_scaled.shape)
print("\nManual scaler result:\n", X_scaled)



Manual scaler result shape: (506, 5)

Manual scaler result:
         LSTAT   PTRATIO       NOX        RM       AGE
0   -1.080991 -1.457558 -0.144075  0.413263 -0.118521
1   -0.499650 -0.302794 -0.739530  0.194082  0.370774
2   -1.213749 -0.302794 -0.739530  1.281446 -0.264952
3   -1.366072  0.112920 -0.834458  1.015298 -0.811390
4         NaN  0.112920 -0.834458  1.227362 -0.511385
..        ...       ...       ...       ...       ...
501       NaN  1.175303  0.157968  0.438881  0.020768
502 -0.508035  1.175303  0.157968 -0.234316  0.292201
503 -0.988759  1.175303  0.157968  0.983986  0.802924
504 -0.871373  1.175303  0.157968  0.724955  0.742209
505 -0.675729  1.175303  0.157968 -0.362408       NaN

[506 rows x 5 columns]


In [37]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def logistic_regression_gd(X, y, lr=0.01, epochs=1000, lam=0.1):
    m, n = X.shape

    w = np.zeros(n)
    b = 0

    loss_history = []
    acc_history = []

    for epoch in range(epochs):
        # Forward pass
        z = X @ w + b
        y_hat = sigmoid(z)

        # ---- LOSS ----
        eps = 1e-15  # numerical stability
        loss = (
            - (1/m) * np.sum(
                y * np.log(y_hat + eps) +
                (1 - y) * np.log(1 - y_hat + eps)
            )
            + (lam/(2*m)) * np.sum(w**2)
        )


        predictions = (y_hat >= 0.5).astype(int)
        accuracy = np.mean(predictions == y)

        # Store
        loss_history.append(loss)
        acc_history.append(accuracy)

        # ---- GRADIENTS ----
        dw = (1/m) * (X.T @ (y_hat - y)) + (lam/m) * w
        db = (1/m) * np.sum(y_hat - y)

        # ---- UPDATE ----
        w -= lr * dw
        b -= lr * db

        # Optional printing
        if epoch % 100 == 0:
            print(f"Epoch {epoch}: Loss = {loss:.4f}, Accuracy = {accuracy:.4f}")

    return w, b, loss_history, acc_history

    w,b,loss_history,acc_history=logistic_regression_gd(X_scaled,y)
    print("Final weights:", w)
    print("Final bias:", b)
    print("Final loss:", loss)


In [29]:
import numpy as np
from sklearn.cluster import KMeans

def kmeans_matrix(M, K, random_state=42):
    """
    Args:
        M : 2D numpy array (H x W)
        K : number of clusters

    Returns:
        assignment_table : same shape as M, cluster labels
        cookbook : dict -> cluster_id : list of (i, j) positions
        centroids : numpy array of centroid values
    """
    H, W = M.shape

    # 1. Convert matrix to feature list
    # Each cell is one data point with 1 feature
    X = M.reshape(-1, 1)

    # 2. Run KMeans
    kmeans = KMeans(n_clusters=K, random_state=random_state, n_init=10)
    labels = kmeans.fit_predict(X)

    # 3. Assignment table (same shape as M)
    assignment_table = labels.reshape(H, W)

    # 4. Cookbook
    cookbook = {k: [] for k in range(K)}
    for i in range(H):
        for j in range(W):
            cluster_id = assignment_table[i, j]
            cookbook[cluster_id].append((i, j))

    # 5. Centroids
    centroids = kmeans.cluster_centers_

    return assignment_table, cookbook, centroids


In [30]:
M = np.array([
    [1, 2, 3],
    [10, 11, 12],
    [2, 3, 4]
])

assignment_table, cookbook, centroids = kmeans_matrix(M, K=2)

print("Assignment Table:\n", assignment_table)
print("Cookbook:\n", cookbook)
print("Centroids:\n", centroids)


Assignment Table:
 [[1 1 1]
 [0 0 0]
 [1 1 1]]
Cookbook:
 {0: [(1, 0), (1, 1), (1, 2)], 1: [(0, 0), (0, 1), (0, 2), (2, 0), (2, 1), (2, 2)]}
Centroids:
 [[11. ]
 [ 2.5]]
